"""
API ENDPOINT TIPS

gameID: YYYYMMDD_AWAY@HOME
"""

import requests
from consts import _API_CONSTS

API_URL, GET_NFL_BOX_SCORE,\
GET_NFL_STATS_SP, GET_DAILY_SCOREBOARD,\
FANTASY_POINT_PROJECTIONS, GET_PLAYER_INFO = _API_CONSTS

